<a href="https://colab.research.google.com/github/Gurkanwalk/Gurkanwalk/blob/main/IRIS_FLOWER_CLASSIFICATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Classification of iris flowers from sepal and petal dimensions using KNN Algorithm.

The aim is to classify iris flowers among three species (setosa, versicolor, or virginica) from measurements of sepals and petals' length and width.

The central goal here is to design a model that makes useful classifications for new flowers or, in other words, one which exhibits good generalization.

In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [54]:
dataset=pd.read_csv('/content/Iris.csv')

In [55]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [56]:
dataset.drop(['Id'],axis=1,inplace=True)

In [57]:
dataset.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [58]:
dataset.shape

(150, 5)

In [59]:
x=dataset.iloc[:,:-1].values # independent variable

In [60]:
y=dataset.iloc[:,4].values  # dependent variable

In [61]:
#Splitting
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [62]:
#Feature scaling
from sklearn.preprocessing import StandardScaler  
scale= StandardScaler()  


In [63]:
x_train=scale.fit_transform(x_train)
x_test=scale.fit_transform(x_test)

In [65]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train,y_train)
knn.fit(x, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [66]:
y_pred=classifier.predict(x_test)


In [68]:
classifier.predict([[3, 5, 4, 2]])

array(['Iris-virginica'], dtype=object)

In [67]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print ("Accuracy of model is:")
print (accuracy_score(y_test,y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      0.82      0.90        11
 Iris-virginica       0.82      1.00      0.90         9

       accuracy                           0.93        30
      macro avg       0.94      0.94      0.93        30
   weighted avg       0.95      0.93      0.93        30

[[10  0  0]
 [ 0  9  2]
 [ 0  0  9]]
Accuracy of model is:
0.9333333333333333
